### PR TITLE
Do not error when there are pipe characters in the eadid

### LINKED ISSUE #783: [PULFALight/production] URI::InvalidURIError: bad URI(is not URI?): "/catalog/MC121|Walter"
When parsing an eadid and component id, we need more processing.
- [x] Drop anything after a pipe (|) in the eadid
- [x] Drop anything after a space in the componentid

Another example of an erroring component id:   "componentid" => "c00003 Scheduled Date"

## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/65922/faults/78580571)

### PR DESCRIPTION
**Pull request by bess**
Fixes #783

### CODE REVIEW

File: lib/pulfalight/traject/ead2_component_config.rb [hunk 1]
```diff
@@ -33,7 +33,7 @@
                    record["id"] = hexdigest
                    hexdigest
                  else
-                   record.attribute("id")&.value&.strip&.gsub(".", "-")&.gsub("aspace_", "")
+                   record.attribute("id")&.value&.strip&.gsub(".", "-")&.gsub("aspace_", "")&.split(" ")&.first
```
Comment (jrgriffiniii) [inline lib/pulfalight/traject/ead2_component_config.rb:36]: 👍

**Review by jrgriffiniii — APPROVED** [review]
