### PR TITLE
Fix breadcrumbs

### LINKED ISSUE #217: Breadcrumb links are broken
The breadcrumbs are assuming the collection ID is in the link, which we've removed.

See https://pulfalight-staging.princeton.edu/catalog/C0396_c0335 for an example.

### PR DESCRIPTION
**Pull request by tpendragon**
Closes #217

### CODE REVIEW

File: app/models/arclight/parent.rb [hunk 1]
```diff
@@ -0,0 +1,22 @@
+# frozen_string_literal: true
+
+module Arclight
```
Comment (jrgriffiniii) [inline app/models/arclight/parent.rb:3]: I have no objections to this, but I recall that `DigitalObject` was placed in `app/overrides` (please see https://github.com/pulibrary/pulfalight/blob/master/app/overrides/arclight/digital_object_override.rb). I would just please prefer that one approach be used consistently.

Comment (tpendragon) [reply app/models/arclight/parent.rb]: Done.
