### PR TITLE
Fix indexing items where there's no parent container info.

### LINKED ISSUE #637: Indexing fails for resources where the parent has no container information.
## Backtrace

    line 277 of [PROJECT_ROOT]/lib/pulfalight/traject/ead2_component_config.rb: replace
    line 277 of [PROJECT_ROOT]/lib/pulfalight/traject/ead2_component_config.rb: block (2 levels) in load_config_file
    line 598 of [PROJECT_ROOT]/lib/pulfalight/traject/ead2_component_config.rb: block (3 levels) in load_config_file

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/65922/faults/74835654)

### PR DESCRIPTION
**Pull request by tpendragon**
This also makes sure container info isn't lost for items which are
"text" but actually have a container.

Closes #637

### CODE REVIEW

File: lib/pulfalight/traject/ead2_component_config.rb [hunk 1]
```diff
@@ -270,35 +270,33 @@
...
     # Text records have no container information, but can be requested. Copy the
     # container info from the parent.
     parent = context.clipboard[:parent] || settings[:parent]
-    accumulator.replace(parent.output_hash["container_location_codes_ssim"])
-  else
-    record.xpath("./did/container").each do |container_element|
-      container_location_code = container_element.attributes["altrender"].to_s
-      accumulator << container_location_code if container_location_code.present?
-    end
+    accumulator.replace(parent.output_hash["container_location_codes_ssim"] || [])
```
Comment (jrgriffiniii) [inline lib/pulfalight/traject/ead2_component_config.rb:281]: 👍

File: lib/pulfalight/traject/ead2_component_config.rb [hunk 2]
```diff
@@ -270,35 +270,33 @@
...
 to_field "container_information_ssm" do |record, accumulator, context|
-  if context.output_hash["level_ssm"] == ["Text"]
+  record.xpath("./did/container").each do |container_element|
+    container_location_code = container_element.attributes["altrender"].to_s
+    container_profile = container_element.attributes["encodinganalog"].to_s
+    next if container_location_code.blank?
+    accumulator << {
+      location_code: container_location_code,
+      profile: container_profile
+    }.to_json
```
Comment (jrgriffiniii) [inline lib/pulfalight/traject/ead2_component_config.rb:293]: 👍

**Review by jrgriffiniii — APPROVED** [review]
