### PR TITLE
Format titles with "bulk" dates

### LINKED ISSUE #571: Collection-level title display is showing dates incorrectly.
Mock-up:Screen Shot 2021-08-30 at 10 27 00 AM

Inclusive dates appear twice and bulk dates have a slash (probably coming from the encoding, normalized formatting) as opposed to a dash between beginning and end dates (DACS formatting). Example: https://findingaids-beta.princeton.edu/catalog/C0062_c000001087. 

Should look like https://pulfa.princeton.edu/collections/C0062/c000001087

The title for this should be

`Booth Tarkington Papers, 1812-1956 (mostly 1899-1946)`

### PR DESCRIPTION
**Pull request by bess**
* Do not duplicate dates when they appear in the title
* Format the "bulk" date as shown

Fixes #571

### CODE REVIEW

File: lib/pulfalight/normalized_date.rb [hunk 1]
```diff
@@ -41,5 +55,20 @@ def valid_ranges?(dates)
 
       true
     end
+
+    # Override from Arclight::NormalizedDate
+    # @see http://www2.archivists.org/standards/DACS/part_I/chapter_2/4_date for rules
+    def normalize
+      if inclusive.present?
+        result = inclusive.to_s
+        result << " (mostly #{bulk})" if bulk.present?
```
Comment (jrgriffiniii) [inline lib/pulfalight/normalized_date.rb:64]: 👍

**Review by jrgriffiniii — APPROVED** [review]
