### PR TITLE
Index components combined fields to *_tsm.

### LINKED ISSUE #1188: Components are indexing combined fields to the wrong field type
Components are indexing to _combined_ssm instead of _combined_tsm.

### PR DESCRIPTION
**Pull request by tpendragon**
Closes #1188

https://github.com/pulibrary/pulfalight/blob/pulfalight_combined_headings/app/models/solr_document.rb#L358

### CODE REVIEW

**Review by hackartisan — APPROVED** [review]

File: spec/services/aspace/indexer_spec.rb [hunk 1]
```diff
@@ -9,6 +9,9 @@
       stub_aspace_resource_ids(repository_id: "13", resource_ids: ["1", "2", "3"])
       stub_aspace_resource_ids(repository_id: "13", modified_since: Time.zone.parse("2020-01-09").to_i, resource_ids: ["3"])
     end
+    after do
+      Timecop.return
```
Comment (hackartisan) [inline spec/services/aspace/indexer_spec.rb:13]: 🎉

**Review by hackartisan — APPROVED** [review]
